# Generated by Django 3.1 on 2020-09-01 11:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, null=True),
        ),
    ]
